### ISSUE TITLE
just: airplane mode

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#113]
I'm on a trip and it'd be a nice to have a just shortcut to disable the autoupdates to everything that we can, especially until updates are more efficient. 

Perhaps there's a way to display that service's status when I open a terminal or something to remind me it's on as a reminder to turn it back on when I'm not on slow internet.

**Comment by tulilirockz** [comment]
This feature would need to encompass both images having ublue-update and the regular gnome-software and discover counterparts, too, I'd think.

**Comment by castrojo** [comment]
I think just turning the flatpak and autoupdate services on and off should do the trick?

**Comment by tunix** [comment]
Network Manager allows us to mark a connection as metered. I don't know where exactly it stores that information but it'd be great if that information was fed into systemd so that you can use that info in your service definition. If we're able to read that maybe we can also incorporate that into a script before firing rpm-ostree/flatpak commands?

**Comment by castrojo** [comment]
Yeah this sounds awesome! The reason I wanted the explicit toggle is the data consumption while I'm on slow networks. "I'm going on a trip, I turn this off until I get back" so I'm not flooding my network with an update while checking my email. 

Smarter network manager support is awesome, that'd be a great thing to have no matter what, so if you want to work on that let's do it! Thanks!

**Comment by bsherman** [comment]
> The reason I wanted the explicit toggle is the data consumption while I'm on slow networks. "I'm going on a trip, I turn this off until I get back" so I'm not flooding my network with an update while checking my email. 

So you want "travel mode" rather than "airplane mode" 😁

**Comment by ArtikusHG** [comment]
@castrojo so do you still want a just command or should I just stick to NetworkManager metered connection?

**Comment by ArtikusHG** [comment]
I decided to do the metered connection first, it seems to be working but looking for testers!

**Comment by ArtikusHG** [comment]
Added disable-updates and enable-updates into ```10-update.just``` (decided to do this on the same PR).

**Comment by tunix** [comment]
Thank you @ArtikusHG for taking responsibility for this!

**Comment by ArtikusHG** [comment]
Hey, uh, it's been almost a week, is this going anywhere? Can someone at least take a quick look at the PR so I can fix it if something is wrong?

**Comment by bsherman** [comment]
> Hey, uh, it's been almost a week, is this going anywhere? Can someone at least take a quick look at the PR so I can fix it if something is wrong?

FYI - i didn't realized you had a PR... it the future, it's helpful to add reviewers on the PR itself

**Comment by ArtikusHG** [comment]
> it's helpful to add reviewers on the PR itself

It doesn't seem like I have the right to request a review on a PR, or did you mean just ping someone in there?

**Comment by bsherman** [comment]
> > it's helpful to add reviewers on the PR itself
> 
> It doesn't seem like I have the right to request a review on a PR, or did you mean just ping someone in there?

Interesting... 

You don't have this gear for choosing approvers?

![2023-10-02T10:33:38,741614219-05:00](https://github.com/ublue-os/config/assets/60557/d44ac351-c2ae-44df-aa47-878eb1fca487)
![2023-10-02T10:33:48,596965386-05:00](https://github.com/ublue-os/config/assets/60557/037acbb3-5718-4efe-98db-9bebf9596f8e)

Thanks for letting me know. I don't want to assume people have access to that widget if they don't.

**Comment by ArtikusHG** [comment]
I might be missing something, but yeah, I don't see that icon
![Screenshot_20231002-235954_1](https://github.com/ublue-os/config/assets/24320212/ec4f4be9-875b-4305-996d-8015f7e69d7c)

**Comment by bsherman** [comment]
> I might be missing something, but yeah, I don't see that icon 

Thank you for the feedback. Good to know!

**Comment by ArtikusHG** [comment]
I think with #123 merged, we can close this issue.

**Comment by tunix** [comment]
Hi. Although this is merged, GNOME still tries to fetch updates and seems to cause a lot of bandwidth. Is there a way to prevent this?
