### ISSUE TITLE
flatpak-system-update.service: start-post operation timed out

### ISSUE THREAD

**Issue by ArtikusHG** [ublue-os/config#117]
For the past week or so, I have noticed that flatpaks did not auto update. I decided to look at the systemd logs and found the following:

```
× flatpak-system-update.service - Flatpak Automatic Update
     Loaded: loaded (/usr/lib/systemd/system/flatpak-system-update.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: timeout) since Tue 2023-09-19 14:15:22 EEST; 1h 53min ago
TriggeredBy: ● flatpak-system-update.timer
       Docs: man:flatpak(1)
    Process: 2390 ExecStartPre=/usr/bin/flatpak --system uninstall --unused -y --noninteractive (code=exited, status=0/SUCCESS)
    Process: 2396 ExecStart=/usr/bin/flatpak --system update -y --noninteractive (code=exited, status=0/SUCCESS)
    Process: 2397 ExecStartPost=/usr/bin/flatpak --system repair (code=exited, status=1/FAILURE)
   Main PID: 2396 (code=exited, status=0/SUCCESS)
        CPU: 28.256s

Sep 19 14:15:21 fedora flatpak[2397]: [49/145] Verifying flathub:runtime/org.freedesktop.Sdk.Locale/x86_64/22.08…
Sep 19 14:15:21 fedora flatpak[2397]: [50/145] Verifying flathub:runtime/org.kde.PlatformTheme.QGnomePlatform/x86_64/5.15-22.08…
Sep 19 14:15:21 fedora flatpak[2397]: [51/145] Verifying flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/21.08…
Sep 19 14:15:22 fedora flatpak[2397]: [52/145] Verifying flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/21.08…
Sep 19 14:15:22 fedora systemd[1]: flatpak-system-update.service: start-post operation timed out. Terminating.
Sep 19 14:15:22 fedora flatpak[2397]: [6B blob data]
Sep 19 14:15:22 fedora systemd[1]: flatpak-system-update.service: Control process exited, code=exited, status=1/FAILURE
Sep 19 14:15:22 fedora systemd[1]: flatpak-system-update.service: Failed with result 'timeout'.
Sep 19 14:15:22 fedora systemd[1]: Failed to start flatpak-system-update.service - Flatpak Automatic Update.
Sep 19 14:15:22 fedora systemd[1]: flatpak-system-update.service: Consumed 28.256s CPU time.
```

I then ran the commands from the unit manually, and each of them completed just fine, updating all the flatpaks. From my understanding, this is caused by the fact that ```flatpak --system repair``` is taking way too long, and getting terminated by systemd, which thinks it froze and is doing nothing.

At first I wanted to suggest simply increasing the timeout for ```ExecStartPost```, but as I was looking for the option in the [systemd service specification](https://www.freedesktop.org/software/systemd/man/systemd.service.html), I found the following:

> Note that ExecStartPre= may not be used to start long-running processes. All processes forked off by processes invoked via ExecStartPre= will be killed before the next service process is run.

So it seems that they don't recommend using this option to run commands that may take a lot of time, and therefore, there is no way to customize the timeout for it - there are only ```TimeoutStartSec```, ```TimeoutStopSec```, and ```TimeoutAbortSec``` (could this be dealt with by changing the service type? I don't know and haven't found a type that alters the behavior of ```ExecStartPost```, either way that would be closer to a workaround rather than an actual fix).

The only solution I see right now is starting all 3 commands in ```ExecStart```, possibly by creating a small shell script (the downside is that this makes debugging more difficult if all 3 commands are in one place? They were probably put in 3 different places for a reason after all).

If you approve of my "just put them all in one place" approach, then I could probably make a PR, if not, let's discuss how we can fix this :)

**Comment by castrojo** [comment]
I'm running into this issue as well, except the repair isn't being killed it just hogs the CPU.

**Comment by bsherman** [comment]
Interesting..

Makes sense though. @ArtikusHG thank you for digging in and doing the hard work of understanding why the problem exists.

I'll do some testing with this.

**Comment by bsherman** [comment]
> If you approve of my "just put them all in one place" approach, then I could probably make a PR, if not, let's discuss how we can fix this :)

I read your whole message but apparently didn't read the last sentence until I had already commented.

I'd welcome your PR! :-)   Good to have more contributions!

My thought, at least test a simple solution before adding a separate script.  If we made the service `Type=oneshot` we could chain the three commands in `ExecStart=` using semi-colons.

Thoughts?

**Comment by ArtikusHG** [comment]
This sounds like a great idea, I was thinking of doing something similar, but I'm not very familiar with systemd, so I was not sure whether we could chain multiple commands together in the unit like this.

I will try to test this locally today and will report the results. Thanks for the suggestion!

**Comment by ArtikusHG** [comment]
@bsherman I tested your proposed fix locally and it worked well! Opened a PR with the fix just as promised :)

**Comment by ArtikusHG** [comment]
Thanks a lot for cooperation! Should we close this now or wait for the new image just to be sure everything works?

**Comment by bsherman** [comment]
> Thanks a lot for cooperation! Should we close this now or wait for the new image just to be sure everything works?

Whichever you prefer.

**Comment by ArtikusHG** [comment]
Then lets wait for tomorrow's image, I'll check the systemd logs if everything looks fine.

**Comment by ArtikusHG** [comment]
```
○ flatpak-system-update.service - Flatpak Automatic Update
     Loaded: loaded (/usr/lib/systemd/system/flatpak-system-update.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead) since Mon 2023-09-25 14:16:06 EEST; 42s ago
TriggeredBy: ● flatpak-system-update.timer
       Docs: man:flatpak(1)
    Process: 2383 ExecStart=/usr/bin/flatpak --system uninstall --unused -y --noninteractive (code=exi>
    Process: 2389 ExecStart=/usr/bin/flatpak --system update -y --noninteractive (code=exited, status=>
    Process: 2718 ExecStart=/usr/bin/flatpak --system repair (code=exited, status=0/SUCCESS)
   Main PID: 2718 (code=exited, status=0/SUCCESS)
        CPU: 1min 27.826s

Sep 25 14:15:49 fedora flatpak[2718]: [140/147] Verifying flathub:runtime/org.freedesktop.Sdk/x86_64/2>
Sep 25 14:16:03 fedora flatpak[2718]: [141/147] Verifying flathub:app/com.dosbox_x.DOSBox-X/x86_64/sta>
Sep 25 14:16:03 fedora flatpak[2718]: [144/147] Verifying flathub:runtime/org.kde.Platform.Locale/x86_>
Sep 25 14:16:03 fedora flatpak[2718]: [147/147] Verifying flathub:runtime/org.libreoffice.LibreOffice.>
Sep 25 14:16:03 fedora flatpak[2718]: Checking remotes...
Sep 25 14:16:03 fedora flatpak[2718]: Pruning objects
Sep 25 14:16:06 fedora flatpak[2718]: Erasing .removed
Sep 25 14:16:06 fedora systemd[1]: flatpak-system-update.service: Deactivated successfully.
```

Everything seems to be working perfectly! Thanks everyone, closing the issue :)
