### ISSUE TITLE
Include Sunshine udev rules

### ISSUE THREAD

**Issue by dannymate** [ublue-os/config#119]
### Describe the package

I'd like to request the package `[Sunshine](https://github.com/LizardByte/Sunshine/tree/master)` because it allows streaming to any device that has access to a Moonlight client with support for AMD, Intel, and Nvidia GPUs for hardware encoding.

It is the best way I've found to stream to any device I want. The stream quality is good and devices with Moonlight are plentiful (i.e. [Nintendo Switch Moonlight Homebrew](https://github.com/XITRIX/Moonlight-Switch)).

One issue I found and I'm not sure it affects Sunshine so much as it's a Moonlight client issue but it's worth mentioning. When the client device performs Wi-Fi scanning it causes Moonlight to hitch on Linux/GNOME. The only way I found to fix that was to set a BSSID on the client to prevent network scans. I'm unsure if this would affect the server-side in the same way.

It is available as a Flatpak however there is some setup that needs to be performed so it'd be ideal if it was baked in. Though as it is available in other packages it's just a nice to have.

### Information on the package

Installed Packages
Name         : sunshine
Version      : 0.20.0
Release      : 1
Architecture : x86_64
Size         : 48 M
Source       : sunshine-0.20.0-1.src.rpm
Repository   : @System
From repo    : @commandline
Summary      : Sunshine is a self-hosted game stream host for Moonlight.
URL          : https://app.lizardbyte.dev
License      : unknown
Description  : DESCRIPTION
             : ===========
             : 
             : This is an installer created using CPack (https://cmake.org). No
             : additional installation instructions provided.

### Image

Bazzite

**Comment by castrojo** [comment]
Moving to the config repo where we do udev rules.

**Comment by ArtikusHG** [comment]
@dannymate fixed it, you can now close the issue

**Comment by akdev1l** [comment]
lgtm
