### ISSUE TITLE
Add UBPorts Installer udev rules

### ISSUE THREAD

**Issue by fiftydinar** [ublue-os/config#129]
Source:
https://docs.ubports.com/en/latest/userguide/install.html#missing-udev-rules

Although, AppImage offers to set this up for you, as shown in this screen:
![Screenshot from 2023-09-30 19-45-15](https://github.com/ublue-os/config/assets/65243233/b01381b0-eb2a-4624-8cb7-6b27da98e80b)

Is it still useful to provide them here?
When clicking to automatically provide it, it places 10-ubports.rules file with the rules mentioned above in /etc/udev/rules.d

**Comment by ArtikusHG** [comment]
I think adding these exact rules makes no sense, as the rules provided by the UBPorts installer seem to be a subset of [51-android.rules](https://github.com/M0Rf30/android-udev-rules/blob/main/51-android.rules), which is a larger, regularly maintained list of udev rules for general Android development. If we were to proceed with this, we should just add the entire set, not only the ones that are required for UBPorts.

**Comment by fiftydinar** [comment]
> I think adding these exact rules makes no sense, as the rules provided by the UBPorts installer seem to be a subset of [51-android.rules](https://github.com/M0Rf30/android-udev-rules/blob/main/51-android.rules), which is a larger, regularly maintained list of udev rules for general Android development. If we were to proceed with this, we should just add the entire set, not only the ones that are required for UBPorts.

That's why I made an issue, & not a pull request. I wondered if android rules have those. Btw, I think that android rules should be here in config, not in main.

I think that this can be closed.

**Comment by ArtikusHG** [comment]
It'd be nice if you could test whether the installation succeeds without clicking "Set up rules automatically", but I'm pretty sure ```51-android.rules``` covers this. Even the docs say this:

> See if /etc/udev/rules.d/51-android.rules exists and contains the rules below. **If not**, add them to the file [...]

**Comment by fiftydinar** [comment]
> It'd be nice if you could test whether the installation succeeds without clicking "Set up rules automatically", but I'm pretty sure `51-android.rules` covers this. Even the docs say this:
> 
> > See if /etc/udev/rules.d/51-android.rules exists and contains the rules below. **If not**, add them to the file [...]

I don't have the device which had Ubuntu Touch anymore, so I cannot test. Comparing files side to side, some rules are there, some rules are missing on 51-android.rules from UBPorts. But UBPorts rules are less secure anyway, so maybe just let this as it is without any changes

**Comment by bsherman** [comment]
> It'd be nice if you could test whether the installation succeeds without clicking "Set up rules automatically", but I'm pretty sure `51-android.rules` covers this. Even the docs say this:
> 
> > See if /etc/udev/rules.d/51-android.rules exists and contains the rules below. **If not**, add them to the file [...]
> 
> > Btw, I think that android rules should be here in config, not in main.
> 
> The rules are in main because they are downloaded at build time, as the file in the upstream project is not static and changes fairly frequently. It would make no sense to track these changes in our downstream repo.

I'll be a bit more specific...  android udev rules are installed in `main` because it is an RPM from our COPR and the spec file is from upstream.  If there was no spec file, the android rules would be getting downloaded in this repo and added as part of the `ublue-os-udev-rules` RPM.

https://github.com/ublue-os/main/pull/362/files

**Comment by fiftydinar** [comment]
I am closing this issue, as the agreement is to not do anything with it. Additional rules don't hurt, so let's just keep it as it is.

If you don't agree with me, or you have an issue related to this, feel free to reopen.
