### ISSUE TITLE
just has inconsistent naming for enable/disable scripts

### ISSUE THREAD

**Issue by bronson** [ublue-os/config#148]
I see at least three styles of enable/disable scripts in `just --list`:

* disable-updates ⬌ enable-updates
* disable-broadcom-wl ⬌ use-broadcom-wl
* use-stock-gamepads ⬌ use-ublue-gamepads

Worth standardizing? Feel free to close if not!

**Comment by castrojo** [comment]
This is related to: https://github.com/orgs/ublue-os/discussions/202

Basically we need someone to propose/reorg the justfiles to make sense since they kinda grew organically. And perhaps we need to add a little file with conventions to use or something like that.

**Comment by HikariKnight** [comment]
I should in theory have some more freetime soon now in December so i will start having a look at reorging just, maybe shrink it down to toggles where we can.

**Comment by HikariKnight** [comment]
after a brief discussion on discord, i will have a look at mocking together a bash script that will check if gum is installed and then either use gum or a basic bash dialog/prompt for toggles, that should at least get us started on cleaning up some of the just commands.

Currently the fallback might look something like this
![image](https://github.com/ublue-os/config/assets/2557889/79949242-803a-4620-8a46-c7fa184ce606)

**Comment by HikariKnight** [comment]
i have a working concept now which works, bit unsure if a helper script for just and configs actually fit in ublue-os/config

invalid choices gets the output piped to STDERR and user gets asked again to pick an option, valid choices gets echoed to STDOUT and then exits, this should at least help us merge many commands into just toggle commands.
![image](https://github.com/ublue-os/config/assets/2557889/e92f4eea-36f7-4d78-9946-d0b80962a24e)

### Proposal for standardized naming scheme
- Toggles to be named `toggle-thing`
- Recipes installing/uninstalling/configuring things to be named `setup-thing` or `configure-thing` which then provides options for what the user wants to do, to avoid complexity we can also just split `setup-` and `configure-` to do their own thing.
- Recipes that only do 1 thing to be named `thing` like `ujust update`

**Comment by castrojo** [comment]
Naming scheme sounds good to me!

**Comment by HikariKnight** [comment]
I will wait for more responses until after December 29th before i start working on this in ublue-os/config.
I will open a PR draft on the 29th so changes can be discussed there while i work on it.

once config is done i will start branching out to the other repos (bazzite, bluefin, kinoite, etc) and take a look (unless someone pings me and tells me they will take care of it themselves)

Think that will be my plan forward regarding this at least.
