### ISSUE TITLE
[Low Priority] Consider `/usr/lib/justfile`

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/config#166]
This should be a low priority request but I think `/usr/lib/justfile` is a better place than `/usr/share/ublue/justfile` is because unlike anything else in `/usr/share`, these files have executable code in it and they are executed indirectly like many other files in `/usr/lib`. I think it fits the unix FHS way better.

**Comment by ArtikusHG** [comment]
Isn't ``/usr/lib`` for **lib**raries? Imo that would be a confusing place for a justfile

**Comment by dnkmmr69420** [comment]
> Isn't `/usr/lib` for **lib**raries? Imo that would be a confusing place for a justfile

systemd unit files, udev rules, other executables are found in individual directories in `/usr/lib`
