### ISSUE TITLE
flatpak-system-update.service fails to start: Cannot autolaunch D-Bus without X11 $DISPLAY

### ISSUE THREAD

**Issue by 1player** [ublue-os/config#168]
```
Dec 04 11:06:17 tranquility systemd[1]: Starting flatpak-system-update.service - Flatpak Automatic Update...
Dec 04 11:06:17 tranquility flatpak[423203]: These runtimes in installation 'system' are pinned and won't be removed; see flat>
Dec 04 11:06:17 tranquility flatpak[423203]:   runtime/org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/23.08
Dec 04 11:06:17 tranquility flatpak[423203]: Nothing unused to uninstall
Dec 04 11:06:18 tranquility flatpak[423210]: error: Cannot autolaunch D-Bus without X11 $DISPLAY
Dec 04 11:06:18 tranquility systemd[1]: flatpak-system-update.service: Main process exited, code=exited, status=1/FAILURE
Dec 04 11:06:18 tranquility systemd[1]: flatpak-system-update.service: Failed with result 'exit-code'.
Dec 04 11:06:18 tranquility systemd[1]: Failed to start flatpak-system-update.service - Flatpak Automatic Update.
```

Looks like https://github.com/flatpak/flatpak/issues/3847

Of course it works when I execute the commands manually. I'm pretty sure it used to work months ago, and it's only recently that I find that my Flatpaks are not updating automatically anymore.

**Comment by ArtikusHG** [comment]
I will (probably) take a look at that tomorrow or in the next few days at least. Was the upstream issue ever resolved? The one you linked doesn't seem so

**Comment by ArtikusHG** [comment]
Unfortunately I cannot reproduce the issue on my machine, the service runs fine for me. Can you provide a bit more details about your system, what image you're using, etc.?

**Comment by 1player** [comment]
I'm on ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-main:39

I've also slightly tweaked the timer because it used to fire when the network was still offline, and kept failing, but nothing that should affect correct operation. Here is the override applied to the timer (with systemctl edit):

[Unit]
After=network-online.target

[Timer]
OnCalendar=*-*-* 11:00:00
OnUnitInactiveSec=6h

This setup used to work for months until recently.

**Comment by ArtikusHG** [comment]
I'm on silverblue and I don't get this, the fact that it's different on kinoite is weird. Does the same error pop up when calling the daemon manually? (not the *command* - the *daemon*, by running ``systemctl start flatpak-system-update.service``)

**Comment by 1player** [comment]
Just fixed this annoying issue by appending `/usr/bin/dbus-launch` to each flatpak invocation in the systemd unit, as suggested by https://github.com/flatpak/flatpak/issues/3847

Snip: 

```
ExecStart=/usr/bin/dbus-launch /usr/bin/flatpak --system uninstall --unused -y --noninteractive ; /usr/bin/dbus-launch  /usr/bin/flatpak --system update -y --noninteractive ; /usr/bin/dbus-launch /usr/bin/flatpak --system repair
```

**Comment by nicorum** [comment]
Hi I get exactly the same error on kinoite. The fix from 1player solves the problem for me. Maybe GNOME starts something in the background which is not started by KDE?
I installed kinoite in january and the flatpak-system-update.service never worked for me.

**Comment by 1player** [comment]
Keep in mind that recent Fedora versions have adopted dbus-broker, so `/usr/bin/dbus-launch` doesn't exist any more but should instead be replaced with `/usr/bin/dbus-run-session`

I noticed a few days ago that my flatpaks were not being updated any more because of this. This is my current ExecStart line for reference: 

```
ExecStart=/usr/bin/dbus-run-session /usr/bin/flatpak --system uninstall --unused -y --noninteractive ; /usr/bin/dbus-run-session  /usr/bin/flatpak --system update -y --noninteractive ; /usr/bin/dbus-run-session /usr/bin/flatpak --system repair
```
