### ISSUE TITLE
Justfile missing in latest builds

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#17]
Looks like the justfile isn't being copied over, need to investigate.

**Comment by castrojo** [comment]
Ok it looks like we need to build the RPM here so it can go into main and then to the downstream derivatives?

**Comment by bsherman** [comment]
Closed by #18 's merge.

Also, i tested both `silverblue-main:38` and `silverblue-nvidia:38` to verify not only is `just` present, but also the included `justfile` is what was expected per the respective images.
