### ISSUE TITLE
Track history of applied just OS modifications

### ISSUE THREAD

**Issue by fiftydinar** [ublue-os/config#171]
# Why
It is useful for tracking modifications you did on top of the OS you may want to revert in the future.
It is useful for troubleshooting issues from the affected users.
It is useful for warning the user if he applied system configuration already (applying same just command which modifies the system twice in a row is dirty, ex. rpm-ostree kargs)

# Example
I want to hide grub & to apply amd_pstate-active manually to the CPU. I apply those commands:

`just hide-grub`
`just amd_pstate-active`

I want to have those in history of applied modifications with timestamp by issuing this (or similar) command:

`just modification-history`

When you apply the command which reverts to defaults with:
`just unhide-grub`
`just revert-amd_pstate-active`

Than those just entries you had in `just modification-history` will get removed.

We would whitelist only those just commands which are related to modifying the system, so we would avoid having something like `just update` in `just modification-history`.

# Implementation
Not something I figured out currently. This is just an idea I got right now. Feel free to start your own work. I will also start my own.

Broadly imagining, we would have the "modifications" file in /usr/share/ublue-os/just & we would include that file in justfile. Modifications file would contain just commands which modify the OS & the "revert to defaults" equivalent just command to pair. That's just the configuration part.

I didn't figure out yet on how to implement the main logic to `just modification-history` command.

**Comment by federdaemn** [comment]
Maybe create history file including timestamps like the 'history' shell command?

**Comment by johnnylam88** [comment]
`just` is just a command runner, similar to `make`, so there are no built-in logging facilities for the commands that are run. You might need to adjust each recipe to log something to an, e.g., `.just_history` file, which would let you know which commands were run, but you would also need each recipe to also have an opposite recipe to undo its changes if you wanted some sort of *revert-to-defaults* command. It seems quite involved.

**Comment by castrojo** [comment]
Yeah we're using this for shortcuts, not active management of the machine.
