### ISSUE TITLE
Migrate justfiles to import

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#178]
https://github.com/casey/just/pull/1779

Just 1.18.x is headed to Fedora soon, I got pinged by the Fedora maintainer with this heads up. Looks like we need to move to `!import` instead of `!include` and then probably swap it out in the `~/.justfile`.

A nice bonus is the feature is stable! cc @ublue-os/approver @ublue-os/member

**Comment by castrojo** [comment]
Upload status: https://bodhi.fedoraproject.org/updates/FEDORA-2023-4bdb1708ac

**Comment by bsherman** [comment]
Also useful for reference: https://packages.fedoraproject.org/pkgs/rust-just/just/

So, version 1.18 is in testing...
