### ISSUE TITLE
`just` issue 

### ISSUE THREAD

**Issue by returntrip** [ublue-os/config#196]
It seems `just` has an issue after this [commit](https://github.com/ublue-os/config/pull/181) (maybe)
```
just
error: Alias `devbox` defined on line 32 is redefined as a recipe on line 116
   ——▶ /usr/share/ublue-os/just/70-nix.just:116:7
    │
116 │ alias devbox := setup-devbox
    │       ^^^^^^
```

**Comment by HikariKnight** [comment]
Downstream issue with bling that was fixed yesterday.
Rebuild your startingpoint image and it will be fixed
