### ISSUE TITLE
Fleek installs outdated version

### ISSUE THREAD

**Issue by bayou-brogrammer** [ublue-os/config#202]
Using `ujsut fleek` and installing fleek via gum, will install fleek v0.9x instead of the latest which is 0.10x

The docs state to use 

```bash
nix run "https://getfleek.dev/latest.tar.gz" -- init
...
<make edits to .fleek.yml>
...
nix run "https://getfleek.dev/latest.tar.gz" -- apply
```

I see where to edit this in `ujust` files, but was curious the implementation you would prefer. Until the user runs `nix run "https://getfleek.dev/latest.tar.gz" -- apply` fleek wont appear in their $PATH

**Comment by bayou-brogrammer** [comment]
@HikariKnight thanks!

**Comment by HikariKnight** [comment]
@bayou-brogrammer np!
