### ISSUE TITLE
Please integrate Realtek 8152/8153/8156 udev-rules to activate the kernel driver

### ISSUE THREAD

**Issue by skyblaster** [ublue-os/config#24]
Description and solution (FYI, not my video):
https://www.youtube.com/watch?v=sAfPm2CxfI4

Link to file: https://github.com/wget/realtek-r8152-linux/blob/master/50-usb-realtek-net.rules

Tested in uBlue and works just fine with my RTL8156 adapter.

Reference: https://www.phoronix.com/news/Realtek-RTL8153-RTL8156-Linux

**Comment by bsherman** [comment]
@skyblaster would you be willing to test a custom `ublue-os-udev-rules` RPM to verify this works for you?

**Comment by skyblaster** [comment]
@bsherman Absolutely. Just let me know where to grab the file from. Thanks!

**Comment by bsherman** [comment]
@skyblaster here's an RPM I've built with the udev rules for you to test.

You should be able to `rpm-ostree override replace ublue-os-udev-rules.noarch.rpm`  to override the already installed version of the RPM. 

After you are done testing, you can `rpm-ostree reset ublue-os-udev-rules` to restore image default.

https://pixeldrain.com/u/vuDo8akd



Side note: I bought one of these adapters and it's arriving this weekend for me to test, too! :-)

**Comment by bsherman** [comment]
Apologies if that override doesn't work as expected... I'm confused here as I don't see the new file with the override, but I'm out of time to test today. I'll follow up with more info tomorrow probably.

**Comment by skyblaster** [comment]
> I don't see the new file with the override

^ Same.
No luck on the first try. The software driver is still being loaded.

>Side note: I bought one of these adapters and it's arriving this weekend for me to test, too! :-)

Nice. I suspect these could pair nicely for folks using uCore.
I bought mine from AliExpress awhile back, but it's essentially this one [here](https://www.ebay.com/itm/275776046871)
I have a Lenovo L13 without built in Ethernet and don't use it very often, but when I do I've found the software driver very unreliable, so I hope the kernel driver works much better.

**Comment by bsherman** [comment]
@skyblaster I was able to test this by manually copying the file  https://raw.githubusercontent.com/ublue-os/config/34ee4b21ad34ca80115a95d8a18fd735c4cb29ad/files/etc/udev/rules.d/50-usb-realtek-net.rules   to `/etc/udev/rules.d` on my ublue machine ... then plugging in the 2.5gbit USB device..

Then I did some iperf3 tests to another machine...
```
[ ID][Role] Interval           Transfer     Bitrate         Retr
[  5][RX-S]   0.00-10.01  sec  2.72 GBytes  2.33 Gbits/sec                  receiver
[  8][TX-S]   0.00-10.01  sec  2.73 GBytes  2.34 Gbits/sec    0             sender
```

Looks pretty good! 

You can do the same if you want, or just wait for this to get merged and in a day or two a reboot should provide you the update.

**Comment by bsherman** [comment]
@skyblaster this was merged ( https://github.com/ublue-os/config/pull/36 ) , the next builds of `ublue-os/main` will include the udev rules.

Would love to hear how it works for you!

**Comment by skyblaster** [comment]
@bsherman Thanks. The r8152 driver now loads as expected.
iperf3 testing looks good up to 1G. I unfortunately do not have any other 2.5Gbps gear to test any faster, lol.

Thanks for implementing! Maybe I should open a ticket with Fedora and see if this can be added upstream.
