### ISSUE TITLE
Apps installed with homebrew in the host don't work in Fish shell after chsh

### ISSUE THREAD

**Issue by bshor** [ublue-os/config#244]
I'm running Bazzite with the latest image.

[I installed homebrew on the host](https://universal-blue.discourse.group/t/installing-cli-apps-on-the-host/979/5). It works great for installing apps into the user directory. My favorite shell, fish, is already pre-installed in Bazzite. Awesome!

But when I try to change shells with ``chsh -s /usr/bin/fish``, the apps I previously installed with homebrew in bash are no longer found.

More curiously, if I enter the fish shell _from_ bash by just typing ``fish``, I **am** able to access the commands I previously installed under bash. But not if I change shells and restart the terminal app (Ptyxis).

**Comment by citrixscu** [comment]
This should be fixed as of a few days ago. See [Issue #1205](https://github.com/ublue-os/bluefin/issues/1205)

**Comment by boredsquirrel** [comment]
please do not change your shell!!! Fish is not POSIX compliant. Try to run a random bash or even shell script in fish, it will likely fail.

You can only change your user shell to a POSIX compliant shell, and maybe there are even things in the OS that depend on bash.

Instead, change the shell for your terminal emulator. In Konsole that works through Profiles, and GNOMEs Console also has a way.
