### ISSUE TITLE
New karg needed for NVIDIA users: `initcall_blacklist=simpledrm_platform_driver_init`

### ISSUE THREAD

**Issue by travier** [ublue-os/config#250]
According to:
- https://github.com/fedora-silverblue/issue-tracker/issues/477#issuecomment-2011283957
- https://github.com/fedora-silverblue/silverblue-docs/pull/175
- https://rpmfusion.org/Howto/NVIDIA#OSTree_.28Silverblue.2FKinoite.2Fetc.29

we apparently need to setup a new karg when using NVIDIA proprietary drivers: `initcall_blacklist=simpledrm_platform_driver_init`

Likely in https://github.com/ublue-os/config/blob/main/build/ublue-os-just/40-nvidia.just.

I've not tested this change.

Thanks

**Comment by bsherman** [comment]
I have a machine which could be used for testing this and a fix, but I've got several other irons in the fire. If someone else what's to verify that they can reproduce and fix the bug, I welcome that.

Otherwise, I'll move this to TODO once I've had a chance to reproduce.

**Comment by m2Giles** [comment]
The proposed fix was added to bluefin/aurora builds as part of the hardware setup script. I personally haven't seen this bug as an Nvidia + LUKS user

**Comment by p5** [comment]
I'm going to close this one, as it seems we've managed to steer clear of this issue.  

Please feel free to reopen or leave a comment if this is still relevant, and we can revisit.
