### ISSUE TITLE
Implement `ujust rollback`

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#252]
It's annoying to rollback, how about:

```
ujust rollback
Image: 󱋩 bluefin-dx:39-20240412                                                       
Rollback to: 
39-20240412
39-20240411
39-20240410
39-20240409
39-20240408
```

And then the selector rebases them to that image.

**Comment by m2Giles** [comment]
We have a template here:

https://github.com/ublue-os/bazzite/pull/1002

**Comment by m2Giles** [comment]
https://github.com/ublue-os/bluefin/pull/1269/

This is my idea

**Comment by castrojo** [comment]
We have this downstream already
