### ISSUE TITLE
Include the SteamOS fix for memory allocation?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/config#27]
I saw this video from Brodie about the compatibility fix that for some reason just gets implemented in F39. Its just a single sysctl override file, I think I already made a pull request. 

Should be essential for some apps, and not break anything.

https://www.phoronix.com/news/Fedora-39-VM-Max-Map-Count

**Comment by noelmiller** [comment]
This is already included in Fedora 39. Fedora 38 will be going EOL in April / May time frame. We recommend updating to Fedora 39 if you want this feature.
