### ISSUE TITLE
ujust: Disable MAC randomization

### ISSUE THREAD

**Issue by fiftydinar** [ublue-os/config#271]
Since Fedora 40 introduced MAC randomization, some users may want to disable it for their configuration, either per network profile or globally.

Until this is implemented in network settings inside desktop environments, just command for this will suffice.

**Comment by fiftydinar** [comment]
Gnome has this option to configure here per-network:

![Screenshot from 2024-05-08 18-05-05](https://github.com/ublue-os/config/assets/65243233/07bfa248-1810-4ebd-91fa-0d91397b1652)

"Permanent" is to disable
"Stable" is to keep it enabled

**Comment by castrojo** [comment]
If people want this they can set this by hand via the gui.
