### ISSUE TITLE
Where is the skel.d directory saved now?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/config#28]
I would like to add something to the first boot script.

**Comment by ArtikusHG** [comment]
/etc/skel is still there, or are you looking for something else?

**Comment by noelmiller** [comment]
/etc/skel and /etc/skel.d are equivalent. Any changes you need to make in /etc/skel.d can be made in /etc/skel. Changes will not be overwritten based on how rpm-ostree works with the /etc directory.
