### ISSUE TITLE
Adding workqueue disabling if user is on SSD

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/config#29]
This is a pretty easy fix, but currently only if you have one SSD partition, so the command will be more complex in the end:

```
lsblk -d -o name,rota | grep -E '^nvme|^sd' | awk '{print $1}' | head -n 1 && printf 'discard,no-read-workqueue,no-write-workqueue' | sudo tee -a /etc/crypttab && notify-send -a "optimizer" "Encrypted SSD performance optimized"
```

This command detects if you have any SSD, and just adds the parameters to the last line of the crypttab file.

Problems:
- only working if one SSD works
- encrypted SSD + encrypted HDD not working

Something building on top of that will be helpful for performance.

**Comment by ArtikusHG** [comment]
I feel like this is out of scope for ublue, if this really gives a significant performance boost you should go to upstream Fedora and try to push it there.
