### ISSUE TITLE
Unversion the container build

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#31]
https://github.com/ublue-os/config/blob/35a73962f7a9289fbf8f89ded27407dffa6cd160/.github/workflows/build.yml#L32

It'll be annoying to update this over time, we should consider unversioning to something else.

**Comment by bsherman** [comment]
Seems to me we have a couple options:

1. unversion: if possible, just depend on "latest" for the build, which at the moment would be "38", to simplify things
2. matrix: not so simple, but would avoid all possible conflicts from different version, or even the confusion of seeing the wrong `fc37` on a `fc38` system
3. short term: regardless of a choice on 1 or 2... seems we probably want to upgrade to 38 soon as it's the new "latest"
