### ISSUE TITLE
`ujust` autocomplete

### ISSUE THREAD

**Issue by Malix-off** [ublue-os/config#312]
Currently, `ujust` doesn't autocomplete (tab doesn't show options)

This would be a nice feature addition

**Comment by KyleGospo** [comment]
Just tested and it does autocomplete, we added this feature many months ago. If you're having a specific issue please open an issue with more details.

**Comment by Malix-off** [comment]
It may be my machine then, I'll open an issue in Bluefin

**Comment by Malix-off** [comment]
@KyleGospo ^
