### ISSUE TITLE
Update openrgb rules

### ISSUE THREAD

**Issue by Arcitec** [ublue-os/config#32]
I just noticed something. The ublue/config OpenRGB rules are severely outdated (missing like 50 new rules). We should definitely have a build step that fetches the freshest rules from upstream automatically.

In the case of OpenRGB, the instructions are posted [on their Flathub page](https://github.com/flathub/org.openrgb.OpenRGB#udev-rules), and says that the latest rules are always at the following URL:

- `https://gitlab.com/CalcProgrammer1/OpenRGB/-/jobs/artifacts/master/raw/60-openrgb.rules?job=Linux+64+AppImage&inline=false`

I dunno how such an automated fetch step should look like, though. I.e. it should probably fall back to the most recently cached file if fetch fails.

We need the same for the other rules too, such as game devices.

If this can be automated, it removes 1 more maintenance burden from uBlue.

**Comment by castrojo** [comment]
It looks like these are in fedora now, I think we'll just remove them from here but then add them in main.

**Comment by Arcitec** [comment]
@castrojo Nice discovery, I see the change:

https://github.com/ublue-os/main/pull/197

What do you think about the other rules, like game-devices? Anything that isn't in Fedora's repos would be nice to automatically fetch from upstream.

**Comment by castrojo** [comment]
The game devices one are updated every day already

**Comment by Arcitec** [comment]
> The game devices one are updated every day already

Brilliant. Is there anything remaining that would benefit from automatic pulling, or should we close this ticket now? :)

**Comment by castrojo** [comment]
Yeah this one is good to go, thanks!
