### ISSUE TITLE
Migrate to just includes.

### ISSUE THREAD

**Issue by EinoHR** [ublue-os/config#48]
I _just_ closed the issue [#27 on startingpoint](https://github.com/ublue-os/startingpoint/issues/27) and am moving it now here.

> `just` seems to be very slow in updating currently. I have a tested solution, though.

> Aliasing `alias just='just --unstable'` works (mostly) perfectly and `just` does not nag about it.
The only problem is that the default recipe in `main.just` errors out.
> ```just
> default:
>    @just --list
> ```
> This can be easily fixed by adding the `--unstable` flag to the command.

These are the two changes I'm proposing;
* Replace the entirety of [`ublue-os-just.sh` ](https://github.com/ublue-os/config/blob/main/build/ublue-os-just/ublue-os-just.sh) with `alias just='just --unstable'`
* Make the default recipe in `main.just` 
    ```just
    default:
        @just --unstable --list
    ```
Furthermore, instruct users to create a `~/.justfile` with the following contents (maybe with a `cat EOF` command to make it extra easy).
```just
!include /usr/share/ublue-os/just/main.just
!include /usr/share/ublue-os/just/nvidia.just
# only enable when using a custom image
# !include /usr/share/ublue-os/just/custom.just
```

The current system is functional, but still feels more of a hack compared to this. I'm also positive [the PR for `just`](https://github.com/casey/just/pull/1588) making it possible to use a environment variable to set the unstable mode won't be merged in a while, as the latest commit touching on the project's code is from January and development seems sluggish there. Not to even say about when the ìnclude directive would be made stable.

**Comment by castrojo** [comment]
Oh nice catch! Yeah let's do this, I put a help wanted tag on it!

**Comment by EinoHR** [comment]
Sure, I'll probably PR this in today.
