### ISSUE TITLE
Add a just shortcut for running mesa-git

### ISSUE THREAD

**Issue by castrojo** [ublue-os/config#57]
We could add an alias that adds the flathub beta repos and launches steam with mesa-git. Here's what I'm doing locally. 

```
systemctl --user set-environment FLATPAK_GL_DRIVERS=mesa-git
systemctl --user restart flatpak-portal.service
FLATPAK_GL_DRIVERS=mesa-git flatpak run com.valvesoftware.Steam
```

We could just put this in the justfile so people have it.

**Comment by ArtikusHG** [comment]
How about we add a just command that runs *anything* with mesa-git? I think Steam is not the only thing that people may want to run with mesa-git, there's also Lutris, Boxes, Cartridges and a few other game launchers on FlatHub. Something like ```just run-mesa-git <enter your command here>```. And also one for installing mesa-git in the first place of course.

**Comment by castrojo** [comment]
Out of scope, closing.
