### ISSUE TITLE
feat: an ublue justfile

### ISSUE THREAD

**Issue by EinoHR** [ublue-os/config#6]
The old base has a justfile with numerous useful commands, it would be a shame to retire it. So how about having it in this repository?

It should also probably be copied to a system directory (if possible) which is not writable to the user, so that it can be updated in the cloud and automatically changed on users systems. 

Then if a custom image or a user wants to have their own justfile for system commands, they can have it in ~/.justfile and use `set fallback` as detailed in https://just.systems/man/en/chapter_56.html?highlight=justfile#fallback-to-parent-justfiles to use both justfiles.

**Comment by castrojo** [comment]
Great idea. Some of those are real old and could use a good scrubbing, so perhaps it might be best to start with the simple no-brainer ones and then expand from there?

**Comment by EinoHR** [comment]
Yeah, I agree. Most of the flatpak setups should probably be left out, and the PWA one should probably take the browser as an argument instead of defaulting to edge.
