### ISSUE TITLE
Centralised Update System

### ISSUE THREAD

**Issue by IlChitarrista** [ublue-os/config#63]
# Objective

The Objective of this suggestion is to reflect and develop a System that can Automatically Manage System Updates from a Centralised Environment without interfering with the usage of the OS and while providing some level of customisability and error reporting.

# Software Support

- rpm-ostree
- flatpak
- distrobox | (toolbox)
- (Fleek / Nix)
- (More?)

The fundamental systems that we need to support are rpm-ostree for the automatic updates while OS Upgrades (38 --> 39) are fine to be handled from Gnome Software as they normally should require more intentionality. Then Flatpak as that is the main method of acquiring software on Immutable systems. Distrobox, while often used for Development, can be a powerful tool to install software which might not have an OS Package or Flatpak (It should also be theoretically preferred to rpm-ostree)(This would be the case, for example, of Reaper).

## Extra Software?

We could also consider supporting Fleek / Nix but I would need someone to contribute extra info on that as I've never used such systems. I also highly incourage anyone to contribute some other system which would need support.

# GUI?

It would be great to have an OS which can be fully interacted both from a GUI and a CLI and this system could have some integration with Gnome Software although this would require a significant ammount of knowledge. This should also be a discussion upstream as pretty much no OS other than [Vanilla OS](https://handbook.vanillaos.org/2022/12/10/updates.html) implements this almost perfectly.

# Basic Flow of Execution

Single Check
```mermaid
graph TB
    A[Start] --> B{Configurable Timer}
    B -->|Every 24h| C[Check for Non-Interruption]
    B -->|Every Week| C
    B -->|Never| D[End]
    C -->|All Conditions OK| E[Check for System Updates]
    C -->|Any Condition Fails| D
    E -->|Updates Available| F[Handle Updates Linearly]
    E -->|No Updates| D
    F -->|Error| G[Notify User and Continue]
    F -->|No Error| H[Proceed to Next System]
    G --> H
    H -->|All Systems Updated| D
    H -->|More Systems to Update| F
```

Multiple Check
```mermaid
graph TB
    A[Start] --> B{Configurable Timer}
    B -->|Every 24h| C[Check for Non-Interruption]
    B -->|Every Week| C
    B -->|Never| D[End]
    C -->|All Conditions OK| E[Check for System Updates]
    C -->|Any Condition Fails| D
    E -->|Updates Available| F[Handle Updates Linearly]
    E -->|No Updates| D
    F --> G{Check for Non-Interruption\nSkip the First time}
    G -->|All Conditions OK| H[Proceed to Next System]
    G -->|Any Condition Fails| D
    H -->|Error| I[Notify User and Continue]
    H -->|No Error| J[Proceed to Next System]
    I --> J
    J -->|All Systems Updated| D
    J -->|More Systems to Update| F
```
The basic Flow of Execution of this tool should be based around some configurable timer (Every 24h | Every Week | Never) which would then run some checks to assure non-interruption (Battery && CPU Usage && Network Usage? && Fullscreen Application (Mostly Games) && More? if checking is enabled) either once or before each system updates (Maybe the User starts to do something while one system is updating therefore it could be an idea, given that the check itself is fast, to stop the tool and reschedule, possibly to a shorter than defined time) as they should be handled linearly (Downloads are already parallelised for each system so running multiple updates from multiple systems in parallel would mostly likely have little improvement).
If any error arises then the tool continues with the other systems while somehow notifying the user of this otherwise nothing is notified.

# Conclusion

This is only a starting point, hopefully someone can actually develop this, as well a more clearly defining it. Thanks :)

**Comment by gerblesh** [comment]
We dicussed this further in the discord
here's some ideas we had:
running `flatpak repair` to clean up flatpaks?
running `distrobox upgrade` for the update daemon
doing system checks for battery and cpu load
configurability? Do we need a GUI or is a text file fine?

i've created a small WIP github repo for this
https://github.com/gerblesh/ublue-update-daemon
feel free to comm

**Comment by noelmiller** [comment]
I believe most of these issues have been addressed or discussed in https://github.com/ublue-os/ublue-update. Since there have been no updates on this issue for a significant amount of time, I would suggest opening issues in [ublue-update](https://github.com/ublue-os/ublue-update) or discussing in the discord as @gerblesh has suggested.
