### ISSUE TITLE
No udev rules.

### ISSUE THREAD

**Issue by pkulak** [ublue-os/config#8]
Currently the udev rules don't make it into the final image. Just wondering if that's intentional, and I'm misreading something, or if you guys would like a PR for that. It'll admit, it's a bit tricky to tell what's going on, and what the expected behavior would be, but I'm happy to give it a shot.

**Comment by castrojo** [comment]
Oh weird, I just confirmed they're missing on my system but have been there in the past, yeah if you have an idea go for it! (I'll start looking too and post any info I find here)

**Comment by bsherman** [comment]
Odd... they are present on my systems... which are on images built from most recent `main` and `nvidia` ublue-os images.

```
$ rpm -ql ublue-os-udev-rules-0.2-1.fc37.noarch
/usr/lib/udev/rules.d/60-openrgb.rules
... snip ...
```

I also rebased to latest `main` to check it and same result.

**Comment by castrojo** [comment]
Oh! Check in `/usr/lib/udev/rules.d`, there they are! Old versions of this put them in `/etc` but that's for the user's rules now.

**Comment by pkulak** [comment]
Oh yeah, there they are! Thanks guys, sorry for the trouble. :D

**Comment by castrojo** [comment]
No need to apologize, extra eyes are always appreciated!
