### ISSUE TITLE
Automated rpm-ostree updates never run

### ISSUE THREAD

**Issue by 1player** [ublue-os/config#87]
The changes in #84 have broken automated updated of ~~flatpaks and~~ rpm-ostree. 

The PR says "If the host machine is suspended or powered down during that time, the timers will execute on next boot." That is incorrect, as the timers are NOT set as Persistent, so unless you machine is up at 4AM (mine isn't), they are never run.

EDIT: the issue is only on the rpm-ostree timer. Flatpak update timer is set as persistent, as expected.

**Comment by fiftydinar** [comment]
Hmm, that is why I did not get rpm-ostree updates. I was right.

**Comment by p5** [comment]
Thanks for pointing this out!  
This should hopefully be fixed in the next update or two

**Comment by castrojo** [comment]
I've kicked off new builds, to get this fix out faster!
