### ISSUE TITLE
Missed flatpak auto-update timers trigger before dbus session exists

### ISSUE THREAD

**Issue by trevnels** [ublue-os/config#89]
After moving from GNOME to Hyprland, I've noticed that my flatpaks are no longer automatically updating. Previously, GNOME Software seemed to handle Flatpak updates. After removing GNOME Software, I expected the [update timers mentioned in the docs](https://universal-blue.org/faq/?h=update#how-do-i-configure-automatic-updates) to continue keeping flatpaks up to date, though this doesn't seem to be the case - manually running `flatpak update` every once in a while results in a significant list of updates from the previous few days.

While the system update timer is triggering, the service it starts is consistently failing. Here's the relevant part of the log from `systemctl status flatpak-system-update.service`:
```
Aug 08 17:03:11 fedora flatpak[1284]: error: Cannot autolaunch D-Bus without X11 $DISPLAY
Aug 08 17:03:11 fedora systemd[1]: flatpak-system-update.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 17:03:11 fedora systemd[1]: flatpak-system-update.service: Failed with result 'exit-code'.
lines 1-17/17 (END)
```

Something to note here is that 17:03:11 was around the time SDDM started right after booting up my system, and I didn't log in for a few minutes after that. It seems like since the system was off for its scheduled time, the update service is being ran immediately after boot instead. It then fails because the update command requires dbus, which isn't present until after I log in.

It also seems like flatpak updates with systemd failing due to dbus has been raised as an issue on flatpak's repo before: https://github.com/flatpak/flatpak/issues/4345, to which the response was:

> This is nothing to do with Flatpak.
> If you want to run programs in a systemd system service that behave as though they are a tiny login session for D-Bus purposes, you should probably either use dbus-run-session(1), or if your OS includes /usr/lib/systemd/user/dbus.socket, register the systemd service as a login session by setting its PAMName= to a PAM stack (see /etc/pam.d or similar) that includes libpam_systemd.
https://github.com/flatpak/flatpak/issues/4345#issuecomment-883522502

However, `dbus-run-session -- flatpak update` seems to fail for me, as flatpak errors with message `A connection to the bus can't be made`

I think setting PAMName for the service is something worth investigating, along with the other solution I saw in a linked issue:  have the update service be a user service instead of system one, which would ensure that it doesn't start until the user actually logs in and dbus is running. `flatpak-user-update.service` is already a user service, and it does run successfully once the user signs in, so it looks like moving `flatpak-system-update.service` into `/usr/lib/systemd/user` would fix the issue.

I'm not sure if a time delay would sufficiently solve the issue, as it's not guaranteed that the user will be signed in within, say, 60 seconds of the system booting.

**Comment by castrojo** [comment]
If they work out feel free to PR them in, that's a subtle bug indeed! (Former FIRST advisor here, always good to see FIRST affiliated folks in open source!)

**Comment by akdev1l** [comment]
if we add `After=dbus-broker.service` that may work

for `PAMName` you could probably try `PAMName=login`

**Comment by bsherman** [comment]
I've been reading man `systemd.timer` and I'm pretty sure we can make this simpler.

Currently we have:
```
[Timer]
OnCalendar=*-*-* 4:00:00
Persistent=true
```

We can add:
```
OnBootSec=2m
RandomizedDelaySec=10m
```

This should add some random delay to the timers which may help with the problem, but also will ensure the timer runs at least 2 minutes after each boot.

This would also address a concern I brought up in Discord about flatpaks not getting updated after reboot, which is a problem for users of nvidia cards where some flatpaks need the updated userspace nvidia runtimes to match the host driver.

**Comment by bsherman** [comment]
I did a test locally to make sure the OnBoot and OnCalendar timers trigger as expected:

Here's the local service with drop-in override:
```
at 17:29:28 ❯ systemctl cat flatpak-system-update.timer 
# /usr/lib/systemd/system/flatpak-system-update.timer
[Unit]
Description=Flatpak Automatic Update Trigger
Documentation=man:flatpak(1)

[Timer]
OnCalendar=*-*-* 4:00:00
Persistent=true

[Install]
WantedBy=timers.target

# /etc/systemd/system/flatpak-system-update.timer.d/override.conf
[Timer]
OnBootSec=2m
RandomizedDelaySec=5m
OnCalendar=*-*-* 18:00:00
Persistent=true

```

This is OnBoot about to trigger:
```
at 17:30:01 ❯ systemctl status flatpak-system-update.timer 
● flatpak-system-update.timer - Flatpak Automatic Update Trigger
     Loaded: loaded (/usr/lib/systemd/system/flatpak-system-update.timer; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/flatpak-system-update.timer.d
             └─override.conf
     Active: active (waiting) since Sat 2023-08-12 17:27:09 CDT; 3min 8s ago
    Trigger: Sat 2023-08-12 17:30:21 CDT; 2s left
   Triggers: ● flatpak-system-update.service
       Docs: man:flatpak(1)
```

This is after it triggers and the service completes:
```
at 17:31:24 ❯ systemctl status flatpak-system-update.timer 
● flatpak-system-update.timer - Flatpak Automatic Update Trigger
     Loaded: loaded (/usr/lib/systemd/system/flatpak-system-update.timer; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/flatpak-system-update.timer.d
             └─override.conf
     Active: active (waiting) since Sat 2023-08-12 17:27:09 CDT; 4min 18s ago
    Trigger: Sat 2023-08-12 18:04:21 CDT; 32min left
   Triggers: ● flatpak-system-update.service
       Docs: man:flatpak(1)

Aug 12 17:27:09 anguirel systemd[1]: Started flatpak-system-update.timer - Flatpak Automatic Update Trigger.
```

This would be applied directly to both our flatpak timer files.

We could also add the RandomizedDelay to the `rpm-ostreed-automatic.timer`, as it should not be run on every boot we won't add the OnBoot to it.
